services:
  # 1. TU BASE DE DATOS
  mariadb:
    image: 'mariadb:11.4'
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${DB_LOCAL_PORT}:3306"
    volumes:
      - ./data_mariadb:/var/lib/mysql
    networks:
      - fenix_network

  # 2. TU APLICACIÓN SPRING BOOT
  app-spring:
    build: .  # Le dice a Docker: "Busca el Dockerfile en esta misma carpeta y constrúyelo"
    environment:
      # Así es como Spring Boot sabrá dónde encontrar a MariaDB
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_SECRET=${JWT_SECRET}

      - HOST_MAIL=${HOST_MAIL}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - fenix_network

# 3. LA RED QUE LOS UNE
networks:
  fenix_network:
    name: fenix_shared_network
    driver: bridge